# Generated by Django 4.0.4 on 2022-07-15 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('difficult', models.CharField(max_length=20, verbose_name='Сложность')),
                ('ytb', models.CharField(blank=True, default='', max_length=255, verbose_name='YouTube')),
                ('is_published', models.BooleanField(default=True, verbose_name='<= будет опубликовано?')),
                ('id_number_1', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 1')),
                ('id_number_2', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 2')),
                ('id_number_3', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 3')),
                ('id_number_4', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 4')),
                ('id_number_5', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 5')),
                ('id_number_6', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 6')),
                ('id_number_7', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 7')),
                ('id_number_8', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 8')),
                ('id_number_9', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 9')),
                ('id_number_10', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 10')),
                ('id_number_11', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 11')),
                ('id_number_12', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 12')),
                ('id_number_13', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 13')),
                ('id_number_14', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 14')),
                ('id_number_15', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 15')),
                ('id_number_16', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 16')),
                ('id_number_17', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 17')),
                ('id_number_18', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='id для задания 18')),
            ],
            options={
                'verbose_name': 'Варианты ЕГЭ',
                'verbose_name_plural': 'Варианты ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='Category_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=10, verbose_name='Максимальные баллы')),
                ('difficult', models.CharField(max_length=20, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Категории для заданий ЕГЭ',
                'verbose_name_plural': 'Категории для заданий ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='Category_Tasks_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильтра')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL-slug')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.category_tasks', verbose_name='Ключ к категории')),
            ],
            options={
                'verbose_name': 'Фильтры для заданий ЕГЭ',
                'verbose_name_plural': 'Фильтры для заданий ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='Theory_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Раздел математики (Теория)',
                'verbose_name_plural': 'Раздел математики (Теория)',
            },
        ),
        migrations.CreateModel(
            name='Theory_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('ytb', models.CharField(blank=True, default='', max_length=255, verbose_name='YouTube')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='<= будет опубликовано?')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.theory_category', verbose_name='Ключ к категории')),
            ],
            options={
                'verbose_name': 'Тема (Теория)',
                'verbose_name_plural': 'Тема (Теория)',
                'ordering': ['time_update'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(verbose_name='Условие')),
                ('solution', models.TextField(verbose_name='Решение')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('photo_condition', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото в условии')),
                ('photo_before', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото перед решением')),
                ('photo_after', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото после решения')),
                ('is_published', models.BooleanField(default=True, verbose_name='<= будет опубликовано?')),
                ('ytb', models.CharField(blank=True, default='', max_length=255, verbose_name='YouTube')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.category_tasks', verbose_name='Ключ к категории заданий')),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.category_tasks_filter', verbose_name='Ключ к категории фильтров для заданий')),
            ],
            options={
                'verbose_name': 'Задания ЕГЭ',
                'verbose_name_plural': 'Задания ЕГЭ',
                'ordering': ['time_update'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время написания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='<= будет опубликован?')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
